[package]
name = "mdbook-imgsize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = "4.4.8"
mdbook = "0.4.35"
serde_json = "1.0.108"
semver = "1.0.20"
